version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:13.7.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run tests!
      - run: yarn test:ci

      - codecov/upload:
          file: coverage/lcov.info
          flags: jest
